#include "camera.h"
#include "canvas.h"
#include "color.h"
#include "computation.h"
#include "intersection.h"
#include "intersections.h"
#include "lights.h"
#include "material.h"
#include "matrix.h"
#include "ray.h"
#include "transform.h"
#include "tuple.h"
#include "world.h"
// shapes
// TODO: move the definitions of these into shared header files in
// their directory for ease of use
#include "plane.h"
#include "shape.h"
#include "sphere.h"
// patterns
#include "checkers_pattern.h"
#include "conical_ring_pattern.h"
#include "gradient_pattern.h"
#include "pattern.h"
#include "radial_ring_pattern.h"
#include "stripe_pattern.h"
