name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev
    - name: create build folder
      run: mkdir build
    - name: run tests
      run: sh ./testing.sh
